#file: noinspection SpringBootApplicationYaml

# Logging
logging:
  config: classpath:logback-console.xml

# jbst
jbst:
  email-configs:
    enabled: true
    username: "<?>"
    password: "<?>"
    from: "<?>"
  utils-configs:
    geo-country-flags-configs:
      enabled: false
    user-agent-configs:
      enabled: false

# ops
ops:
  server-configs:
    base-url: "http://localhost:8973"
    credentials:
      username: "admin"
      password: "admin"
  servers-configs:
    mode: "RESOURCES"
    rsa-keys-base-location: "~/Dropbox/Tech1/rsa-keys"
  recipients-configs:
    to:
      - "<?>"
  tech1-slack-configs:
    enabled: true
    app-token: "<?>"
    bot-token: "<?>"
    communication:
      channel: ops-founders
    teams-communications:
      - team: SMART_APPS
        communication:
          enabled: false
          channel: ops-team-smart-apps
      - team: TECH1
        communication:
          enabled: false
          channel: ops-founders
  smart-apps-slack-configs:
    enabled: false
    app-token: "<?>"
    bot-token: "<?>"
    communication:
      channel: ops-founders

