#file: noinspection SpringBootApplicationYaml

# Spring Security: actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# jbst
jbst:
  server-configs:
    name: "ops-server"
    springdoc-enabled: false
    maven-configs:
      group-id: @project.groupId@
      artifact-id: @project.artifactId@
      version: v@project.version@
  utils-configs:
    geo-locations-configs:
      enabled: false
  async-configs:
    thread-name-prefix: "ops-async"
    threadsCorePoolPercentage: 50
    threadsMaxPoolPercentage: 100
  events-configs:
    thread-name-prefix: "ops-events"
    threadsCorePoolPercentage: 50
    threadsMaxPoolPercentage: 100
  email-configs:
    host: "smtp.gmail.com"
    port: 587

# ops
ops:
  servers-configs:
    monitoring-configs:
      zone-id: "Europe/Kyiv"
      hide-ip: false
      file-system-filter: 25
      file-system-threshold: 75
  tech1-slack-configs:
    communication:
      enabled: true
  smart-apps-slack-configs:
    communication:
      enabled: true
  keywords-configs:
    services:
      GATEWAY:
        root-cmd: gateway
        commands:
          HELP:
            key: help
            description: "Shows infrastructure.bot [options ...]"
            permissions: FOUNDERS,TEAM
          STATUS:
            key: status
            description: "Executes basic sequence of commands to verify required features"
            permissions: FOUNDERS
      MONITORING:
        root-cmd: mon
        commands:
          SHOW:
            key: show
            description: "Shows servers online statuses: OK / Failure markers"
            permissions: FOUNDERS,TEAM
          ACTUATORS:
            key: actuators
            description: "Shows servers actuator /info (ONLY spring-boot servers)"
            permissions: FOUNDERS
          RELOAD:
            key: reload
            description: "Reloads server-$profile.json configuration"
            permissions: FOUNDERS
      FS:
        root-cmd: fs
        commands:
          SHOW:
            key: show
            description: "Shows servers file systems metadata"
            permissions: FOUNDERS
  messages-configs:
    service-header: ":cloud: Service: *%s* :cloud:"
    response-info: ":information_source: Executed operation response: *%s*"
    response-warning: ":warning: Executed operation response. Please resolve provided warning!"
    over-expensive-operation: ":arrows_counterclockwise: Current operation is over-expensive. Please wait a moment..."
    server-history: "%s Server: *%s*"
