services:
  jbst-server:
    image: ghcr.io/yyluchkiv/jbst-server-iam:1.75-SNAPSHOT
    restart: "no"
    container_name: jbst-server
    networks:
      - network-jbst
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - SPRING_BOOT_PROFILE=mongodb
      - CONFIG_LOCATIONS=classpath:application.yml,classpath:application-dev.yml,classpath:application-mongo.yml,file:/application-docker-mongo.yml
      - JASYPT_PASSWORD=JJJJBSTGH
      - JVM_ARGUMENTS=-Xmx5g -XX:+UseZGC -XX:+ZGenerational --add-opens=java.base/java.time=ALL-UNNAMED
    volumes:
      - ./application-docker-mongo.yml:/application-docker-mongo.yml

  jbst-database-mongodb:
    image: mongo:6.0.15
    restart: "no"
    container_name: jbst-database-mongodb
    ports:
      - "3004:27017"
    networks:
      - network-jbst
    volumes:
      - volume-jbst-mongodb:/data/db

networks:
  network-jbst:
    name: network-jbst
    driver: bridge

volumes:
  volume-jbst-mongodb:
    name: volume-jbst-mongodb
