# Logging
logging:
  config: classpath:logback-console.xml

# jbst
jbst:
  app:
    springdoc-enabled: true
    webclient-url: http://localhost:3000
  utils:
    geolocations:
      enabled: false
    countries-flags:
      enabled: false
    users-agents:
      enabled: false
  incidents-manager:
    enabled: true
    type: "SERVER"
    remote-server:
      base-url: http://localhost:8973
      credentials:
        username: admin
        password: admin
    incidents:
      AUTHENTICATION_LOGIN: true
      AUTHENTICATION_LOGIN_FAILURE_USERNAME_PASSWORD: false
      AUTHENTICATION_LOGIN_FAILURE_USERNAME_MASKED_PASSWORD: true
      AUTHENTICATION_LOGOUT: false
      AUTHENTICATION_LOGOUT_MIN: false
      SESSION_REFRESHED: true
      SESSION_EXPIRED: false
      REGISTER_MAGICLINK: true
      REGISTER0: true
      REGISTER0_FAILURE: true
      REGISTER1: true
      REGISTER1_FAILURE: true
  emails:
    enabled: false
  mvc:
    cors:
      allowed-origins:
        - http://localhost:3003
        - http://localhost:8686
        - http://localhost:8787
  security:
    cookies:
      domain: localhost
    jwt-tokens-configs:
      secret-key: ENC(GbnDNQVCspqW74HYwR6XePbdG6dmo7l/rIPe+hL7uHSnj+5kkUQsj0ZPegUGytLpx/5pdLO7vdQ=)
      storage-method: COOKIES
      access-token:
        expiration:
          amount: 30
          unit: MINUTES # @java.time.temporal.ChronoUnit
      refresh-token:
        expiration:
          amount: 60
          unit: MINUTES # @java.time.temporal.ChronoUnit
    logging-configs:
      advanced-request-logging-enabled: false
    session-configs:
      clean-sessions-by-expired-refresh-tokens-cron:
        enabled: true
        expression: "*/30 * * * * *"
        zone-id: "Europe/Kyiv"
      enable-sessions-metadata-renew-cron:
        enabled: true
        expression: "*/30 * * * * *"
        zone-id: "Europe/Kyiv"
    essense:
      users-on-init:
        enabled: true
        users:
          - username: admin11
            password: "$2a$11$qzm4DlVWEssSavOV0Qf0JOzxQZPIlwl8ja5KlQmBn2QtK7G7bSx3C"
            zone-id: "Europe/Kyiv"
            password-change-required: false
            authorities: [ "admin", "invitations:write" ]
          - username: superadmin11
            password: "$2a$11$qzm4DlVWEssSavOV0Qf0JOzxQZPIlwl8ja5KlQmBn2QtK7G7bSx3C"
            zone-id: "Europe/Kyiv"
            password-change-required: false
            authorities: [ "superadmin", "invitations:read", "invitations:write" ]
      invitations-on-init:
        enabled: true
  databases:
    mongo:
      enabled: true
      database:
        host: jbst-mongodb
        port: 27017
        name: jbst
