#file: noinspection SpringBootApplicationYaml

# Logging
logging:
  config: classpath:logback-console.xml

# jbst
jbst:
  server-configs:
    name: jbstshm-dev

# server
jbst-server-hardware-monitoring:
  server-configs:
    target-url: http://localhost:3002
