#file: noinspection SpringBootApplicationYaml

# Server
server:
  servlet:
    context-path: /api

# Spring Security: actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# jbst
jbst:
  app:
    name: "ops-server"
    springdoc-enabled: false
    maven:
      group-id: @project.groupId@
      artifact-id: @project.artifactId@
      version: v@project.version@
  utils:
    geolocations:
      enabled: false
  async:
    thread-name-prefix: "jbstops-async"
    threads-core-pool-percentage: 50
    threads-max-pool-percentage: 100
  events:
    thread-name-prefix: "jbstops-events"
    threads-core-pool-percentage: 50
    threads-max-pool-percentage: 100
  email-configs:
    host: "smtp.gmail.com"
    port: 587

# server
jbst-server-ops:
  servers-configs:
    monitoring-configs:
      zone-id: "Europe/Kyiv"
      hide-ip: false
      file-system-filter: 25
      file-system-threshold: 75
