#file: noinspection SpringBootApplicationYaml

# Server
server:
  servlet:
    context-path: /api

# Spring Security: actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: ["health", "info"]

# Jasypt
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# jbst
jbst:
  app:
    name: "ops-server"
    springdoc-enabled: false
    maven:
      group-id: @project.groupId@
      artifact-id: @project.artifactId@
      version: v@project.version@
  utils:
    geo-locations-configs:
      enabled: false
  async-configs:
    thread-name-prefix: "jbstops-async"
    threadsCorePoolPercentage: 50
    threadsMaxPoolPercentage: 100
  events-configs:
    thread-name-prefix: "jbstops-events"
    threadsCorePoolPercentage: 50
    threadsMaxPoolPercentage: 100
  email-configs:
    host: "smtp.gmail.com"
    port: 587

# server
jbst-server-ops:
  servers-configs:
    monitoring-configs:
      zone-id: "Europe/Kyiv"
      hide-ip: false
      file-system-filter: 25
      file-system-threshold: 75
