services:
  jbst-database-postgres:
    image: postgres:14.3
    restart: "no"
    container_name: jbst-database-postgres
    ports:
      - "3004:5432"
    networks:
      - network-jbst
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=jbst
    volumes:
      - volume-jbst-postgres:/var/lib/postgresql/data

networks:
  network-jbst:
    name: network-jbst
    driver: bridge

volumes:
  volume-jbst-postgres:
    name: volume-jbst-postgres
