#file: noinspection SpringBootApplicationYaml

# Spring PostgreSQL
spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
  liquibase:
    change-log: classpath:postgres/changelog.yml

# jbst
jbst:
  app:
    name: jbst-server-iam-postgres
