services:
  jbst-database-mongodb:
    image: mongo:6.0.15
    restart: "no"
    container_name: jbst-database-mongodb
    ports:
      - "3004:27017"
    networks:
      - network-jbst
    volumes:
      - volume-jbst-mongodb:/data/db

networks:
  network-jbst:
    name: network-jbst
    driver: bridge

volumes:
  volume-jbst-mongodb:
    name: volume-jbst-mongodb
